### ISSUE TITLE
`myria-cluster` does something, but seems to hang

### ISSUE THREAD

**Issue by arokem** [uwescience/myria-ec2-ansible#25] opened 2016-07-01 21:11 UTC
EC2 instances are started and running, but the CLI seems to hang, and does not return the message that I would expect from the document here: http://myria.cs.washington.edu/docs/myria-ec2.html (the message starting with: `Your new Myria cluster 'test-cluster' has been launched`...).

In additional information, running the following in another terminal window: 

```
(py2) D-140-142-30-42:~  $myria-cluster list arokem --region us-west-2
```

Returns this list (no hosts?):

```
WORKER_IDS HOST                                              
---------- ----                                              
0                                                            
1                                                            
2                                                            
3                                                            
4                
```

Meanwhile, in the EC2 management console, none of the instances have a public DNS, and the IP seems to be only within the virtual private network.

**Comment by senderista** [comment] 2016-07-01 23:02
Provisioning may take several minutes, and doesn't generate log messages unless you specify the `--verbose` or `-v` option. IOW, the CLI will appear to hang until all provisioning has been completed.

If you are trying to launch a cluster within a VPC with no internet gateway, that could also be your problem. Could you paste the exact CLI command you used to launch this cluster? If you launched it in the VPC `vpc-9e3b46fa` ("arokem-myria"), then that does appear to have an internet gateway configured.

What I think is most likely is that your cluster has been launched in a VPC, but you're not specifying `--vpc-id` to the `myria-cluster list` command. After deployment is complete, the CLI will print the complete commands for listing, starting, stopping and destroying the cluster, including the correct VPC ID, but before then you're on your own. Could you try running the `list` command with the correct `--vpc-id` value?

**Comment by arokem** [comment] 2016-07-01 23:07
I'd use the `vpc-id` option, but see #24

**Comment by arokem** [comment] 2016-07-01 23:09
Thanks for pointing out the `verbose` flag - that does bring up a bunch of information.

**Comment by senderista** [comment] 2016-07-01 23:12
#24 is not blocking you from using the `--vpc-id` option with all commands except `create` (I apologize for the asymmetry, but AWS simply won't choose a default subnet for instance launch like they will choose a default AZ for classic/default VPC). Did you try the `list` command with `--vpc-id`? It should work fine.

**Comment by arokem** [comment] 2016-07-01 23:18
Ah! Gotcha. Will keep trying, but not today...

**Comment by senderista** [comment] 2016-07-02 00:06
I think I found the problem: the subnet `subnet-c644889e` (assuming you're using that to launch your cluster) has "Auto-assign Public IP" set to "no", as you can verify in the AWS console. Apparently all my VPC testing so far has been on subnets configured to auto-assign public IPs. Rather than have you change this setting, though, I'll modify the script to explicitly force auto-assigned public IPs and have you verify that it now works with your existing configuration. There's no reason for the script not to do that anyway, since it's important to be able to SSH into all cluster nodes for diagnostic purposes.

**Comment by senderista** [comment] 2016-07-02 06:31
fixed in 164f171
I tested on your subnet with `myria-cluster create ip-test --subnet-id subnet-c644889e`
You should pick up this change with `pip install --upgrade myria-cluster`

**Closed as completed by senderista** 2016-07-02 06:31 UTC

**Comment by arokem** [comment] 2016-07-05 02:24
Upon updating, I am now getting a message that: 

```
py2) chlosyne:~  $myria-cluster create test --subnet-id subnet-c644889e --verbose
WORKER_MEM_GB: 4.0
AMI_ID: ami-d75392b7
CLUSTER_SIZE: 5
VERBOSE: 1
EC2_INI_PATH: /var/folders/jz/4k438hl91v7gvdd592ct4lpc0000gn/T/tmp8j8V6G
SUBNET_ID: subnet-c644889e
NODE_MEM_GB: 6.0
REGION: us-west-2
CLUSTER_LOG_LEVEL: WARN
ansible_python_interpreter: /usr/bin/env python
PRIVATE_KEY_FILE: /Users/arokem/.ssh/arokem-myria_us-west-2.pem
IAM_USER: arokem
CLUSTER_NAME: test
INSTANCE_TYPE: t2.large
KEY_PAIR: arokem-myria
NODE_VCORES: 2
DATA_VOLUME_SIZE_GB: 20
VPC_ID: vpc-9e3b46fa
WORKERS_PER_NODE: 1
WORKER_VCORES: 1
USER: arokem
PLAY [Create AWS resources]
TASK [Create EC2 keypair if absent]
ok: [localhost]
TASK [Check for existing private key file]
ok: [localhost]
TASK [Fail if new keypair was created but private key file already exists]
skipping: [localhost]
TASK [Fail if keypair already exists but private key file is missing]
skipping: [localhost]
TASK [Save private key to file]
skipping: [localhost]
TASK [Create security group for this cluster]
changed: [localhost]
TASK [Tag security group to designate as Myria cluster]
changed: [localhost]
TASK [Launch instances]
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Instance creation failed => AuthFailure: Not authorized for images: [ami-d75392b7]"}
PLAY RECAP [localhost] : ok: 4 changed: 2 unreachable: 0 skipped: 3 failed: 1
Failed to initialize EC2 instances, destroying cluster...
Deleting security group test (sg-e4ca5182)
Security group test (sg-e4ca5182) successfully deleted
```

**Comment by senderista** [comment] 2016-07-05 05:18
Sorry for this unrelated regression; I switched to custom AMIs and forgot to make them public. I just successfully created a cluster under the uwescience account, so you should be OK now.

**Comment by arokem** [comment] 2016-07-05 14:52
Yep. Everything working as expected now.
